### ISSUE TITLE
Include the mainfile fix

### ISSUE THREAD

**Issue by hubdotcom** [jsdelivr/api-sync#27]
Referenced here https://github.com/jsdelivr/jsdelivr/pull/4077#issuecomment-92716170

**Comment by UnbounDev** [comment]
@jimaek, unless I am misunderstanding the issue, it seems like the appropriate solution would be to include a `mainfile` field w/i each `assets` version block; e.g.
```
http://api.jsdelivr.com/v1/jsDelivr/libraries/imagesloaded 

//=>
{
   ...
    "assets": [
      {
        "version": "2.1.0",
        "mainfile": "jquery.imagesloaded.min.js",
        "files": [
          "jquery.imagesloaded.js",
          "jquery.imagesloaded.min.js",
          "mainfile"
        ]
      },
     ...
    ],
   ...
}
```

Api-sync would populate this field by checking for the existence of 'mainfile' w/i the `files` array and pulling the content from github, else it would default the value to that provided by the ini file, the bot would then check against the version blocks `mainfile` value when validating.

**Comment by jimaek** [comment]
Yes, api-sync would need to look for those files and read them to populate that field. Also the `files` array needs to remove the actual  file called `mainfile` from the list of files.

**Comment by UnbounDev** [comment]
@jimaek the fix is in on this side! http://api.jsdelivr.com/v1/jsDelivr/libraries/imagesloaded

**Comment by jimaek** [comment]
Nice!
