### ISSUE TITLE
Github rate limiting

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api-sync#36]
Any ideas how to overcome them?
If the problem is a single huge project then we could discuss to remove it from the API completely.

**Comment by UnbounDev** [comment]
Yea this is becoming a major issue as the number of projects grows - honestly the only fool proof method would be to move to a platform that allows us to clone the repos, the initial clone would be costly but every 'sync' event would be nothing more that a `git pull` + analyze the diff.

Baring that ^, is the github token being used by any other applications? We should have a github user dedicated to api-sync so token usage is completely segregated from other applications - it's also possible to have to github users set aside for this purpose and alternate between their tokens during the sync process.

**Comment by jimaek** [comment]
We already clone the repo for libgrabber and its a huge pain in the ass. I want to avoid it at all costs.
I can add an other user to double the rate limit but except from this are there any other solutions?

**Comment by megawac** [comment]
Contact github and ask for a ratelimit increase?

**Comment by jimaek** [comment]
thats in my plans as well. Just wanted to make sure that there is nothing we can do in the code to improve the situation

**Comment by jimaek** [comment]
Github responded and they dont do permanent limit increases.

**Comment by jimaek** [comment]
I can use jsdelivrbot's token and mine. 
Here is what they also said:

>If a maintainer decides to give you a token -- using that is fine. That's actually the benefit of creating an OAuth application and asking the users of your service to sign into that application so that you can get a token from them -- that way, your total rate limit increases with the number of your users.

**Comment by megawac** [comment]
Really, they're recommending OAuth token pooling
