### ISSUE TITLE
Define api-sync data response model versions

### ISSUE THREAD

**Issue by markcarver** [jsdelivr/api-sync#48]
It's quite clear from https://github.com/jsdelivr/api/issues/56 that this project does not differentiate between api "versions". This needs to be fixed so we can have have reliable endpoints.

**Comment by MartinKolarik** [comment]
Currently, the same api-sync database is used by both versions, so the data model is a mix of both versions, and each api response needs to be formatted depending on the used version. This "formatting" means that for every project, we need to select which properties should be returned and change their structure if there's a difference between versions (e.g. `assets`).

This isn't ideal, but works, as long as the method of building a list of projects on the CDN doesn't change. Ironically, to make a change like #46 without changing behavior of v1, we'd have to add code to v1 to filter out the new projects on every request. This approach is maybe easier in the short-term, but every change in api-sync means more complex code in all api versions, and a chance of introducing a breaking change if something is overlooked.

The only way I can see to fix this is having a separate database for each API version.

**Comment by markcarver** [comment]
> the data model is a mix of both versions

Then you clearly do not understand what API versioning is or rather what it is intended to solve. You cannot call these "versions". At this rate, the differences between `v1` and `v2` are really just "ideas" of versioning. They are not associated, in any way, with what is actually consumed by an endpoint.

https://www.mnot.net/blog/2011/10/25/web_api_versioning_smackdown
https://www.mnot.net/blog/2012/12/04/api-evolution

> This "formatting" means that for every project, we need to select which properties should be returned and change their structure if there's a difference between versions

Yes. What you're referring to as "formatting" is actually what API versioning is. I understand that at some point the idea of what the response data model is for `v1` and `v2` is going to differ. This is how APIs evolve and become "better".

What jsDelivr are failing to realize (and produce) is that if it wishes to "mix" (backwards compatible) features or response data model properties/keys, then you have to duplicate code to provide the same "effect". You cannot just simple change the existing response data modal.

The point is:

**You cannot change or remove existing parameters/keys from an API. Period.**

That would constitute an API as "unstable" and "unreliable" (which has been par for the course). If you wish to cleanup or migrate something in the data response model, you would have to do so in a new version because it would be a "major break" from what existing code what written for. An example of what constitutes a "major break":

https://developer.github.com/v3/versions/#differences-from-beta-version

> Ironically, to make a change like #46 without changing behavior of v1, we'd have to add code to v1 to filter out the new projects on every request.

No you don't. Real API versioning means that you have multiple code bases (branches, projects, etc.). Any code, and I mean any, that even remote touches the API should be "version aware" so it can produce the correct response data model for each API "version" it needs to. There is never a need to "filter stuff out" if you work in a specific version's code base from the beginning.

> The only way I can see to fix this is having a separate database for each API version.

Exactly! As I stated in the other issue, jsDelivr is authoritative here. The reason jsDelivr is authoritative is because it is the one that is taking an existing source, parsing it and then reconstructing it into whatever response data model it's outputting.

Thus, this means that jsDelivr is now that one creating a _new source_ (because it does not reflect the original data you parsed). However you choose store this newly constructed data is up to you really, but my guess is that keeping two different databases would be the easiest solution.

This all being said, I would imagine that if you really don't want to keep two database then you'll probably have to obfuscate this project to an even _more_ "internal" tool and create a new intermediate "response" project that is responsible for constructing the appropriate versioned endpoints (e.g. `api-response` or whatever).

**Comment by MartinKolarik** [comment]
>Then you clearly do not understand what API versioning is or rather what it is intended to solve.

Actually, I perfectly understand what API versioning is, and I agree with most of your points. I started working on this project about a week ago, and my comment above was just a summary of the current situation.

@jimaek thoughts?

**Comment by markcarver** [comment]
@MartinKolarik, I'm sorry, I didn't me "you" specifically... I meant more of how this project as a whole has treated "versioning". I'm still trying to learn how to not personalize and escalate problems with my responses. Please bear with me. Has just been a very frustrating past 24hrs (on my end).

**Comment by jimaek** [comment]
I am really sorry for the troubles that this change caused. When I reviewed the PR I didn't realize that it would have impact on v1 as well. If I knew that at the time under no circumstances I would merge it.
Thats the whole point of v2, to do all the breaking changes there and leave v1 as is with all of its problems as is.
I take the responsibility here and will make sure nothing similar happens ever again.

Also since I am not a node.js developer I cant comment on what is the best way to implement that functionality. From my end that requirement is that it needs to work on v2 and leave v1 alone.
But I think maintaining 2 DB files would not be that hard or require any maintenance in the future.
We can then map each json file to v1 and v2 respectfully.
Is that as easy as I think it is? Are there better solutions?

**Comment by MartinKolarik** [comment]
>Is that as easy as I think it is? Are there better solutions?

It's not that hard, and I think it's the most robust solution. The biggest downside is it would double memory usage which is already relatively high, but it shouldn't be a big problem.

**Comment by markcarver** [comment]
> I didn't realize that it would have impact on v1 as well.

Yes, which is why different code bases (branches, all [sub-]projects, etc.) is really important for "versioning" APIs. It helps diminish the "manual human error" aspect of things. If the PR had been merged into a hypothetical `v2` branch for instance, this issue would never have occurred (since the hypothetical `v1` branch would be untouched).

> Also since I am not a node.js developer I cant comment on what is the best way to implement that functionality

Interesting. I'm curious then, why was Node.js chosen and by whom? I have some experience with Node.js, but my speciality is more front end (JS) related.

> From my end that requirement is that it needs to work on v2 and leave v1 alone.
> But I think maintaining 2 DB files would not be that hard or require any maintenance in the future.
> We can then map each json file to v1 and v2 respectfully.

Yes!

> Are there better solutions?

Technically speaking, I have no idea ATM since I'm not all that familiar with all the internals of jsDelivr. However from a architectural/QA perspective, perhaps one of the simplest "solutions" would be for me to "officially" help out a bit?

I'm really good at seeing the "big picture" of things. Also, considering that I'm actually already quite heavily invested in needing/keeping this service, would it be fair to ask (at the very least) if maybe y'all ping me when any "bootstrap/bootswatch" stuff is about to happen before it's actually deployed?

**Comment by jimaek** [comment]
@MartinKolarik The RAM usage should not be that big. The bootstrap repo and DB are very small compared to other CDNs we have. If you agree on this solution then lets do that. Unless you can think of something even easier to implement that works.

> Interesting. I'm curious then, why was Node.js chosen and by whom? I have some experience with Node.js, but my speciality is more front end (JS) related.

The original API was written by a contributor for free. He knew node.js best so he used that. It made no sense to re-write everything in PHP or something else when he became less active.

> 
I'm really good at seeing the "big picture" of things. Also, considering that I'm actually already quite heavily invested in needing/keeping this service, would it be fair to ask (at the very least) if maybe y'all ping me when any "bootstrap/bootswatch" stuff is about to happen before it's actually deployed?

I would love that. You can simply subscribe to the 2 API related repos to get emails about everything happening. And I will try to ping you in the comments when its related to bootstrap.

Btw do you have any feedback for v2 in general? https://github.com/jsdelivr/api/tree/v2
Since its not live yet we can still change anything we want.

**Comment by MartinKolarik** [comment]
>The RAM usage should not be that big. The bootstrap repo and DB are very small compared to other CDNs we have.

If we were to do this, I meant for all CDNs, to completely separate the versions. There's no point in doing it only for bootstrap.

**Comment by jimaek** [comment]
Why not? The rest dont have any issues.

**Comment by markcarver** [comment]
> If we were to do this, I meant for all CDNs, to completely separate the versions. There's no point in doing it only for bootstrap.

Agreed. There shouldn't be special cases.

> Why not? The rest dont have any issues.

Because this isn't a "bootstrap/bootswatch" specific problem, this is an "API versioning" problem for jsDelivr itself. Every time a new version is created, you have to essentially fork the previous version and create a new database for that new version. Thus, this would affect all projects.

> The original API was written by a contributor for free. He knew node.js best so he used that. It made no sense to re-write everything in PHP or something else when he became less active.

Agreed. I was just curious. I would certainly be willing to help out here (over time). My recent involvement with publishing some node.js/grunt based packages has been fun and a great learning curve.

> I would love that. You can simply subscribe to the 2 API related repos to get emails about everything happening. And I will try to ping you in the comments when its related to bootstrap.

Yes. I've held off because my inbox is generally already overflowing from the various projects I'm apart of. I would perhaps prefer manual pings (is there an gitter/IRC channel y'all use by chance?) when it's particularly related to bootstrap for now. Perhaps over time (when I have the time), I will become more involved.

> Btw do you have any feedback for v2 in general? https://github.com/jsdelivr/api/tree/v2
> Since its not live yet we can still change anything we want.

I haven't looked at any of the internal code yet. And since there's no working v2 URL, even for beta, I haven't really seen any real output. Perhaps I can spend some time this weekend to get some local instances of all these projects up and running. Maybe even start creating issues/submitting some PRs?

**Comment by MartinKolarik** [comment]
@jimaek See my first comment. They do, the issues just weren't that serious so far. E.g. when I added the repository field, I also had to update v1 code to exclude that field from v1.

**Comment by MartinKolarik** [comment]
@markcarver

>And since there's no working v2 URL, even for beta, I haven't really seen any real output. Perhaps I can spend some time this weekend to get some local instances of all these projects up and running.

https://jsdelivr-api.herokuapp.com/v2

**Comment by jimaek** [comment]
@MartinKolarik If you believe thats the best way then lets do it. 

@markcarver We are all here https://gitter.im/jsdelivr/jsdelivr
Also regarding v2 you can just check the README for most of the stuff and tell us what you think. And Martin left the beta URL
